# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2a87d2a43473107c4082fdc8a2da155aa747c89246468d254d31061f3a8cbbfd3811a1fb3d53c9aba9d545f24005d652cefb70a7cbafc77297a406be9d4eba

test:
  secret_key_base: 74a16db7ac91507fe5ba6bed988aafc84069f0c6432378c78a3b1e77b66b54c0c8a52685bf45ce3ff00fe07aa17971d97c06e0b073614085266560c55b6c72d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
